TournamentTracker.UI/TournamentTracker.UI/Models/Enums.cs
namespace TournamentTracker.UI.Models
{
    public enum TournamentType
    {
        ClassicLeague,
        Head2Head,
        Knockout
    }
}

TournamentTracker.UI/TournamentTracker.UI/Models/ErrorViewModel.cs
namespace TournamentTracker.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TournamentTracker.UI/TournamentTracker.UI/Models/Team.cs
using System.ComponentModel.DataAnnotations;

using TournamentTracker.UI.Models;

public class Team
{
    [Key]
    public int Id { get; set; }
    [Required]
    public string? TeamName { get; set; }
    public string CellNumber { get; set; }
    public int Point { get; set; }
}

TournamentTracker.UI/TournamentTracker.UI/Models/Tournament.cs
using System.ComponentModel.DataAnnotations;

namespace TournamentTracker.UI.Models;


public class Tournament
{
    [Key]
    public int Id { get; set; }
    [Required]
    public string? TournamentName { get; set; }
    public string? Description { get; set; }
}

TournamentTracker.UI/TournamentTracker.UI/Controllers/HelloWorldController.cs
using Microsoft.AspNetCore.Mvc;
using TournamentTracker.UI.Models;

namespace TournamentTracker.UI.Controllers
{
    public class HelloWorldController : Controller
    {
        public IActionResult Index()
        {
            return View(_persons);
        }

        public IActionResult Create()
        {
            var person = new Person();
            return View(person);
        }

        public IActionResult CreatePerson(Person person)
        {
            _persons.Add(person);
            return RedirectToAction(nameof(Index));
            //return View("Index");
        }


        private static List<Person> _persons = new List<Person>();
    }
}

TournamentTracker.UI/TournamentTracker.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TournamentTracker.UI.Models;

namespace TournamentTracker.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TournamentTracker.UI/TournamentTracker.UI/Controllers/TournamentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using TournamentTracker.UI.DataAccess;
using TournamentTracker.UI.Hubs;
using TournamentTracker.UI.Interfaces;
using TournamentTracker.UI.Models;

namespace TournamentTracker.UI.Controllers
{
    public class TournamentController : Controller
    {
        public TournamentController(ITournamentRepository tournamentRepository)
        {
            _tournamentRepository = tournamentRepository;
        }

        //GET
        public async Task<IActionResult> Index()
        {
            //var data = _context.Tournaments.ToList();
            IEnumerable<Tournament> data = await _tournamentRepository.GetAll();
            return View(data);
        }

        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        public IActionResult Create(Tournament obj)
        {
            if (ModelState.IsValid)
            {
                _tournamentRepository.Create(obj);
                return RedirectToAction("Index"); 
            }
            return View(obj);
        }

        public IActionResult Edit(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _tournamentRepository.GetByIdAsync(id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }

            return View();
        }

        [HttpPost]
        public IActionResult Edit(Tournament obj)
        {
            if (ModelState.IsValid)
            {
                _tournamentRepository.Update(obj);
                return RedirectToAction("Index");
                //return RedirectToAction("Index", "Category");
            }
            return View();
        }


        //private readonly ApplicationDbContext _context;
        private readonly ITournamentRepository _tournamentRepository;
    }
}

TournamentTracker.UI/TournamentTracker.UI/Views/HelloWorld/Create.cshtml
@model Person


<div class="row">
    <div class="col-6">

        <div class="card">

            <div class="card-header">
                <h5>Create a new Person</h5>
            </div>
            <div class="card-body">
                <form asp-controller="HelloWorld" asp-action="CreatePerson" method="post">

                    <div class="mb-3">
                        <label class="form-label">Person Name</label>
                        <input asp-for="FirstName" class="form-control" />
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Person Number</label>
                        <input asp-for="CellPhoneNumber" class="form-control" />
                    </div>

                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
            <div class="card-footer"></div>

        </div>

        
    </div>
</div>

TournamentTracker.UI/TournamentTracker.UI/Views/HelloWorld/Index.cshtml
@model List<Person>

<ul>
    @foreach (var obj in Model)
    {
        <li>My first name is @obj.FirstName with phone number @obj.CellPhoneNumber</li>
    }
</ul>

TournamentTracker.UI/TournamentTracker.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TournamentTracker.UI/TournamentTracker.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TournamentTracker</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/bootwatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TournamentTracker.UI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Tournament Tracker App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
                            <span class="visually-hidden">(current)</span>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link" href="#">Features</a>
                        </li>*@
                        @*<li class="nav-item">
                            <a class="nav-link" href="#">Pricing</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Fantasy
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item " asp-controller="Tournament" asp-action="Create">New Tournament</a></li>
                                <li><a class="dropdown-item" asp-controller="Tournament" asp-action="Index">Tournaments</a></li>
                               @* <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Others</a></li>*@
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container">
            &copy; 2023 - TournamentTracker.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TournamentTracker.UI/TournamentTracker.UI/Views/Tournament/ClassicLeague.cshtml
<h1>Classic League</h1>

TournamentTracker.UI/TournamentTracker.UI/Views/Tournament/Create.cshtml
@*@model Tournament


<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Tournament</h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="TournamentName" class="p-0"></label>
            <input asp-for="TournamentName" class="form-control" />
            <span asp-validation-for="TournamentName" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Description" class="p-0"></label>
            <input asp-for="Description" class="form-control" />
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Create</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Tournament" asp-action="Index" class="btn btn-secondary form-control border">Back to List</a>
            </div>
        </div>
    </div>
</form>*@

@model Tournament

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Tournament</h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="TournamentName" class="p-0"></label>
            <input asp-for="TournamentName" class="form-control" />
            <span asp-validation-for="TournamentName" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Description" class="p-0"></label>
            <input asp-for="Description" class="form-control" />
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button id="sendButton" type="submit" class="btn btn-primary form-control">Create</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Tournament" asp-action="Index" class="btn btn-secondary form-control border">Back to List</a>
            </div>
        </div>
    </div>
</form>

<script src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>
<script src="~/js/Tour.js"></script>

TournamentTracker.UI/TournamentTracker.UI/Views/Tournament/Edit.cshtml
@model Tournament

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Category</h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="TournamentName" class="p-0"></label>
            <input asp-for="TournamentName" class="form-control" />
            <span asp-validation-for="TournamentName" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Description" class="p-0"></label>
            <input asp-for="Description" class="form-control" />
            @*<span asp-validation-for="DisplayOrder" class="text-danger"></span>*@
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Update</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Tournament" asp-action="Index" class="btn btn-secondary form-control border">Back to List</a>
            </div>
        </div>



    </div>
</form>

TournamentTracker.UI/TournamentTracker.UI/Views/Tournament/Head2Head.cshtml
<h1>Head2Head</h1>

TournamentTracker.UI/TournamentTracker.UI/Views/Tournament/Index.cshtml
@model IEnumerable<Tournament>

<div class="container">

    <div class="p-3">
        <table class="table table-bordered table-striped table table-hover">
            <thead>
                <tr>
                    <th>
                        Tournament Name
                    </th>
                    <th>
                        Description
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td> <a href="#">@obj.TournamentName</a></td>
                        <td>@obj.Description</td>

                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Tournament" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-dark mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-controller="Tournament" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>

                    </tr>
                }

            </tbody>

        </table>
    </div>
    <div class="row p-1">
        <div class="col-6">
            <ul id="messagesList"></ul>
        </div>
    </div>
    
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

TournamentTracker.UI/TournamentTracker.UI/Views/Tournament/Knockout.cshtml
<h1>Knockout</h1>